import type { Metadata } from "next";
import { SiteFooter, SiteHeader } from "../site-chrome";
import { serviceDetails } from "../services-data";

export const metadata: Metadata = { title: "Services | Small Shop SOS", description: "Creative, technical and practical support for small businesses: branding, websites, copy, ecommerce, product data and VA/admin help.", alternates: { canonical: "/services/" } };

export default function ServicesPage() {
  return <main className="route-page services-overview"><SiteHeader />
    <style>{`.services-overview .services-hero{padding:clamp(68px,10vw,130px) clamp(24px,9vw,130px) clamp(48px,7vw,90px);background:#1a1a1f;color:#f6f3ef}.services-hero h1{max-width:850px;margin:12px 0 25px;font:700 clamp(58px,8.2vw,112px)/.9 var(--display);letter-spacing:-.07em}.services-hero .lead{max-width:720px;color:#ebe6e8;font-size:clamp(17px,1.8vw,21px);line-height:1.65}.services-hero .eyebrow{color:#e4b6cc}.service-intro{max-width:920px;padding:clamp(54px,8vw,108px) clamp(24px,9vw,130px) 26px}.service-intro h2,.not-a-box h2{margin:10px 0 20px;font:700 clamp(36px,5vw,66px)/.95 var(--display);letter-spacing:-.055em}.service-intro p,.not-a-box p{max-width:740px;font-size:17px;line-height:1.75}.service-list{padding:24px clamp(24px,7vw,100px) clamp(65px,9vw,120px);display:grid;gap:18px}.service-row{display:grid;grid-template-columns:minmax(170px,.45fr) minmax(260px,1fr) minmax(140px,.32fr);gap:clamp(20px,4vw,65px);align-items:end;padding:clamp(26px,4vw,52px);border-top:1px solid #cbc4c1;background:#fff;color:#1a1a1f;text-decoration:none;transition:background .18s ease,color .18s ease}.service-row:last-child{border-bottom:1px solid #cbc4c1}.service-row:hover{background:#5a2a4a;color:#fff}.service-row:hover .service-row__price,.service-row:hover .service-row__link{color:#f1d8e5}.service-row h2{margin:8px 0 0;font:700 clamp(31px,4vw,55px)/.94 var(--display);letter-spacing:-.055em}.service-row p{margin:0;max-width:600px;font-size:15px;line-height:1.65}.service-row__price{align-self:center;color:#5a2a4a;font:700 22px/1.05 var(--display)}.service-row__link{display:block;margin-top:22px;color:#5a2a4a;font-size:11px;font-weight:800;letter-spacing:.05em;text-decoration:underline;text-underline-offset:5px;text-transform:uppercase}.not-a-box{padding:clamp(58px,8vw,110px) clamp(24px,9vw,130px);background:#e9e3e2}.not-a-box>div{max-width:900px}.not-a-box .cta-set,.services-ending .cta-set{display:flex;gap:13px;flex-wrap:wrap;margin-top:28px}.services-ending{padding:clamp(60px,9vw,125px) clamp(24px,9vw,130px);background:#5a2a4a;color:#fff}.services-ending h2{max-width:830px;margin:9px 0 17px;font:700 clamp(44px,6vw,80px)/.9 var(--display);letter-spacing:-.06em}.services-ending p{max-width:620px;color:#f4e9ee;font-size:17px;line-height:1.7}.services-ending .cta.light{background:#f6f3ef;color:#1a1a1f}.services-ending .plain-link{align-self:center;color:#fff;font-size:12px;font-weight:800;text-decoration:underline;text-underline-offset:5px}@media(max-width:760px){.service-row{grid-template-columns:1fr;gap:13px}.service-row__price{font-size:26px}.service-intro p,.not-a-box p,.services-ending p{font-size:16px}}`}</style>
    <section className="services-hero"><p className="eyebrow">SERVICES</p><h1>What do you need sorting?</h1><p className="lead">You do not need the technical term for it. You do not need to know which platform is causing it. You do not even need to know exactly what has gone wrong. Tell me what you are trying to do, or what is currently doing your head in, and we will start there.</p></section>
    <section className="service-intro"><p className="eyebrow">CREATIVE DIGITAL MECHANIC</p><h2>One person. A lot of useful places to start.</h2><p>Small Shop SOS brings creative, technical and practical business support together. That means you do not have to find a different person every time the job crosses into something else. I can make the thing, build the thing, write the thing, sort the thing behind the thing, and keep a sensible eye on what it all has to do in the real world.</p></section>
    <section className="service-list" aria-label="Small Shop SOS services">{Object.entries(serviceDetails).map(([slug, service]) => <a key={slug} className="service-row" href={`/services/${slug}/`}><div><p className="eyebrow">{service.eyebrow}</p><h2>{service.title}</h2></div><p>{service.summary}</p><div><span className="service-row__price">{service.prices[0].price}</span><span className="service-row__link">Explore {service.title} →</span></div></a>)}</section>
    <section className="not-a-box"><div><p className="eyebrow">REAL BUSINESSES</p><h2>And sometimes it does not fit neatly into a service.</h2><p>That is fine. A website job can turn into copy. An ecommerce problem can turn out to be a data problem. You might need branding today, a flyer next month and help untangling a catalogue six months later.</p><p>Real businesses do not operate in tidy little boxes, and neither do I. You do not have to work out what to call the job before you contact me.</p><p><strong>Tell me what you are trying to achieve. We will work out the rest from there.</strong></p></div></section>
    <section className="services-ending"><p className="eyebrow">READY WHEN YOU ARE</p><h2>Got something that needs sorting?</h2><p>If you already know what you need, tell me about the project. If you are not quite sure where to start, book a time and we will talk it through.</p><div className="cta-set"><a className="cta light" href="/work-with-me/">Tell me about your project →</a><a className="plain-link" href="/book/">Book a time →</a></div></section>
    <SiteFooter />
  </main>;
}
