import { notFound } from "next/navigation";
import { SiteFooter, SiteHeader } from "../../site-chrome";

export const metadata = {
  robots: { index: false, follow: false },
};

type Project = { image:string; media?:string[]; category:string; label:string; title:string; intro:string; role:string; work:string; tools:string; result:string; service:string; serviceHref:string; related:string };

const projects: Record<string, Project> = {
  "small-shop-sos": { image:"/assets/portfolio/sos-site-working-screenshot.png", media:["/assets/portfolio/sos-site-working-screenshot.png","/assets/portfolio/sos-site-review-screenshot.png"], category:"Websites & development", label:"Owned-brand project", title:"Small Shop SOS", intro:"This is my professional digital home: one place for the creative work, websites, writing, ecommerce know-how and practical support people hire me for.", role:"I created the brand direction, wrote the copy, planned the UX and page structure, and built the frontend.", work:"I built the current Small Shop SOS experience as a proper working website: responsive layouts, real routes, navigation and a practical journey from “what do I need?” to “right, I can help with that.” The images here are working site screens, not a logo pretending to be a website.", tools:"Figma, VS Code, GitHub, HTML, CSS, JavaScript and Cloudflare-based delivery.", result:"An owned-brand website I use to show the full range of what I do, without pretending I am a giant agency.", service:"Need a website built or sorted?", serviceHref:"/services/websites/", related:"tada-co" },
  "tada-co": { image:"/assets/portfolio/susie-social.png", category:"Social & content", label:"Paid client work", title:"The TaDa Co / Susie", intro:"This is genuine paid social-content work for Susie Reive’s VA and personal-concierge business.", role:"I designed social content and built a consistent visual system around it.", work:"I created practical branded graphics and recurring social content that could work together as a recognisable system, rather than leaving Susie with one nice-looking post and nowhere to go next.", tools:"Content planning, Canva and social-content formats.", result:"A cohesive set of client-facing social assets. Susie’s PeoplePerHour review reads: “Really amazing work - so pleased - thank you :)”", service:"Need social content that looks like yours?", serviceHref:"/services/content-copy/", related:"words-by-marnie" },
  "acorn-to-oak": { image:"/assets/portfolio/acorn-brand-board.png", category:"Branding & design", label:"Proposal / brand concept", title:"Acorn to Oak", intro:"This is a brand-identity proposal, shown honestly as concept work rather than a commissioned client project.", role:"I designed the logo direction, identity development and application thinking.", work:"I built the direction around a tree-and-roots identity, then explored how the mark, typography and palette could behave across practical applications, including embroidery and merchandise.", tools:"Brand research, identity development and presentation design.", result:"A complete concept direction showing logo-system and application thinking.", service:"Need a logo or a whole identity?", serviceHref:"/services/branding-design/", related:"wellness-house" },
  "karate-veckring": { image:"/assets/portfolio/karate-brand-board.png", category:"Branding & design", label:"Proposal concept", title:"Karaté Veckring France", intro:"This is a proposal identity direction for a karate-club brief, not completed commissioned work.", role:"I developed the logo, badge thinking and practical application design.", work:"I explored an intertwined K/V direction alongside colour, typography, badge, stationery and apparel considerations. The point was to make the mark usable beyond a website screen.", tools:"Identity development and apparel/print application planning.", result:"A considered proposal showing how a club identity can travel from a badge to real-world uses.", service:"Need branding that works beyond a screen?", serviceHref:"/services/branding-design/", related:"acorn-to-oak" },
  "words-by-marnie": { image:"/assets/portfolio/marnie-writing.png", category:"Writing & content", label:"Published work", title:"Words by Marnie", intro:"I am a published author as well as a copywriter and content writer.", role:"I write, edit and shape commercial copy.", work:"My published work includes The Shape of Red Wool, The Mirror and the Vessel and Raven Bay. I also write website copy, product descriptions, ecommerce content, blogs, SEO-conscious content, social copy and editing.", tools:"Research, writing, editing and content planning.", result:"A real writing practice alongside the practical words businesses need to sell, explain and be understood.", service:"Need words that sound like you?", serviceHref:"/services/content-copy/", related:"tada-co" },
  "wellness-house": { image:"/assets/portfolio/wellness-brand-board.png", category:"Branding & design", label:"Concept presentation", title:"Wellness House", intro:"This is a nutritional-supplement branding concept, honestly labelled as concept work.", role:"I created the identity, packaging and visual-system direction.", work:"I developed the logo, typography, product-range presentation, colours, icons and packaging direction as one considered visual system.", tools:"Brand identity, packaging presentation and visual direction.", result:"A concept presentation that shows range in branding and packaging work without claiming a client commission.", service:"Need your brand to look pulled together?", serviceHref:"/services/branding-design/", related:"nocturna-beauty" },
  "nocturna-beauty": { image:"/assets/portfolio/nocturna-brand-board.png", category:"AI & digital", label:"AI-assisted concept", title:"Nocturna Beauty", intro:"This is an AI-assisted beauty concept, included to show a different visual direction and an honest use of AI-assisted exploration.", role:"I directed the creative approach and AI-assisted visual exploration.", work:"I explored identity, packaging and editorial direction using AI-assisted creative workflows. It is presented as a concept, not as paid client work.", tools:"AI-assisted visual workflows and presentation design.", result:"A clearly labelled concept demonstrating range and an honest use of new tools.", service:"Got an idea that needs making?", serviceHref:"/services/branding-design/", related:"small-shop-sos" },
};
export function generateStaticParams(){ return Object.keys(projects).map((slug)=>({slug})); }

export default async function Project({params}:{params:Promise<{slug:string}>}) {
  const {slug}=await params; const p=projects[slug]; if(!p) notFound();
  return <main className="route-page project-page"><SiteHeader />
    <style>{`.case{max-width:1140px;margin:0 auto;padding:clamp(45px,8vw,112px) clamp(22px,6vw,72px)}.case h1{max-width:900px;margin:10px 0 35px;font:700 clamp(54px,9vw,108px)/.86 var(--display);letter-spacing:-.07em}.case-image{width:100%;max-height:650px;object-fit:cover;border:1px solid #d8d3ce;background:#eee9e5}.case-media{display:grid;grid-template-columns:1fr 1fr;gap:14px;margin-top:14px}.case-media img{width:100%;border:1px solid #d8d3ce}.case-grid{display:grid;grid-template-columns:1.1fr .9fr;gap:clamp(34px,8vw,115px);margin-top:46px}.case-grid p{font-size:16px;line-height:1.7}.case-details{display:grid;gap:20px}.case-details div{padding-top:18px;border-top:1px solid #d8d3ce}.case-details h2{margin:0 0 8px;color:#5a2a4a;font-size:10px;letter-spacing:.11em;text-transform:uppercase}.case-details p{margin:0;font-size:13px;line-height:1.6}.case-actions{display:flex;gap:14px;flex-wrap:wrap;margin-top:42px}@media(max-width:720px){.case-grid,.case-media{grid-template-columns:1fr}}`}</style>
    <article className="case"><a className="back-link" href="/portfolio/">← Back to Portfolio</a><p className="eyebrow">{p.label}</p><p style={{color:"#5a2a4a",fontSize:10,fontWeight:800,textTransform:"uppercase",letterSpacing:".1em"}}>{p.category}</p><h1>{p.title}</h1><img className="case-image" src={p.image} alt={p.title+" project evidence"} />{p.media && <div className="case-media">{p.media.slice(1).map(src=><img key={src} src={src} alt="Small Shop SOS working website screen" />)}</div>}<div className="case-grid"><div><p className="lead">{p.intro}</p><p>{p.work}</p></div><div className="case-details"><div><h2>What I did</h2><p>{p.role}</p></div><div><h2>Tools I used</h2><p>{p.tools}</p></div><div><h2>What it shows</h2><p>{p.result}</p></div></div></div><div className="case-actions"><a className="cta" href={p.serviceHref}>{p.service} →</a><a className="textcta" href={"/portfolio/"+p.related+"/"}>Related project →</a><a className="textcta" href="/work-with-me/">Work with me →</a></div></article><SiteFooter />
  </main>;
}
