"use client";

import { createClient, type Session } from "@supabase/supabase-js";
import { useEffect, useState } from "react";

const OWNER = "smallshopsos@gmail.com";

type Section = "dashboard" | "blog" | "services" | "pages" | "media" | "reviews" | "settings" | "seo" | "burt";
type Row = Record<string, any>;
const slugify = (v: string) => v.toLowerCase().trim().replace(/[^a-z0-9]+/g, "-").replace(/(^-|-$)/g, "");
const safeHtml = (v: string) => v.replace(/<script[\s\S]*?<\/script>/gi, "").replace(/\son\w+=(?:"[^"]*"|'[^']*'|[^\s>]+)/gi, "");

export default function AdminClient({ supabaseUrl, supabaseKey }: { supabaseUrl: string; supabaseKey: string }) {
  const supabase = supabaseUrl && supabaseKey ? createClient(supabaseUrl, supabaseKey, {
    auth: { persistSession: true, autoRefreshToken: true },
  }) : null;
  const [session, setSession] = useState<Session | null>(null), [loading, setLoading] = useState(true);
  const [email, setEmail] = useState(OWNER), [notice, setNotice] = useState(""), [section, setSection] = useState<Section>("dashboard");
  const [posts, setPosts] = useState<Row[]>([]), [services, setServices] = useState<Row[]>([]), [reviews, setReviews] = useState<Row[]>([]), [media, setMedia] = useState<Row[]>([]), [settings, setSettings] = useState<Record<string, Row>>({});
  const allowed = session?.user.email?.toLowerCase() === OWNER;
  const load = async () => {
    if (!supabase || !allowed) return;
    const [p,s,r,m,g] = await Promise.all([
      supabase.from("cms_posts").select("*").order("updated_at", {ascending:false}), supabase.from("cms_services").select("*").order("display_order"), supabase.from("cms_reviews").select("*").order("display_order"), supabase.from("cms_media").select("*").order("created_at", {ascending:false}), supabase.from("cms_settings").select("*")
    ]);
    setPosts(p.data || []); setServices(s.data || []); setReviews(r.data || []); setMedia(m.data || []); setSettings(Object.fromEntries((g.data || []).map((x:Row)=>[x.setting_key,x.setting_value])));
  };
  useEffect(()=>{ if(!supabase){setLoading(false);return;} supabase.auth.getSession().then(({data})=>{setSession(data.session);setLoading(false);}); const {data}=supabase.auth.onAuthStateChange((_e,s)=>setSession(s)); return ()=>data.subscription.unsubscribe(); },[]);
  useEffect(()=>{ if(allowed) load(); },[allowed]);
  const signIn = async (e:React.FormEvent) => { e.preventDefault(); if(!supabase)return; if(email.toLowerCase().trim()!==OWNER){setNotice("This is Marnie’s private admin. Use the Small Shop SOS owner email.");return;} const {error}=await supabase.auth.signInWithOtp({email:OWNER,options:{emailRedirectTo:`${window.location.origin}/admin/`}});setNotice(error?error.message:"Check your email for your secure sign-in link.");};
  if(loading)return <main className="admin-shell">Checking your secure admin session…</main>;
  if(!supabase)return <main className="admin-shell"><h1>Admin setup is not connected yet.</h1></main>;
  if(!session)return <main className="admin-shell admin-login"><section><p className="admin-eyebrow">SMALL SHOP SOS</p><h1>Owner admin</h1><p>Private content controls for Marnie. This is not the public website.</p><form onSubmit={signIn}><label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} required /></label><button className="admin-primary">Send secure sign-in link →</button></form>{notice&&<p className="admin-notice">{notice}</p>}</section></main>;
  if(!allowed)return <main className="admin-shell admin-login"><section><h1>This admin is private.</h1><p>This signed-in account is not allowed to manage Small Shop SOS.</p><button onClick={()=>supabase.auth.signOut()}>Log out</button></section></main>;
  const nav: [Section,string][] = [["dashboard","Dashboard"],["pages","Pages"],["services","Services"],["blog","Blog"],["media","Media"],["reviews","Reviews"],["settings","Site Settings"],["seo","SEO"],["burt","Burt"]];
  return <main className="admin-shell"><header className="admin-top"><a href="/" aria-label="Back to Small Shop SOS">S<span>O</span>S</a><div><p>Small Shop SOS owner admin</p><button onClick={()=>supabase.auth.signOut()}>Log out</button></div></header><div className="admin-layout"><nav>{nav.map(([key,label])=><button key={key} className={section===key?"active":""} onClick={()=>setSection(key)}>{label}</button>)}</nav><section className="admin-content">{section==="dashboard"&&<Dashboard go={setSection}/>} {section==="blog"&&<Blog rows={posts} refresh={load} tell={setNotice}/>} {section==="services"&&<Services rows={services} refresh={load}/>} {section==="reviews"&&<Reviews rows={reviews} refresh={load}/>} {section==="media"&&<Media rows={media} refresh={load}/>} {section==="settings"&&<Settings title="Site settings" settingKey="business" value={settings.business||{}} refresh={load}/>} {section==="burt"&&<Settings title="Burt" settingKey="burt" value={settings.burt||{}} refresh={load} burt/>} {section==="pages"&&<Pages/>} {section==="seo"&&<Seo posts={posts} services={services}/>} {notice&&<p className="admin-toast">{notice}</p>}</section></div></main>;
}

function Dashboard({go}:{go:(s:Section)=>void}){return <><p className="admin-eyebrow">DASHBOARD</p><h1>Right. What needs updating?</h1><p className="admin-lead">This changes your content inside the approved Small Shop SOS design. It does not give anyone a button to accidentally redesign the website.</p><div className="admin-grid">{[["blog","Write a blog","Draft, preview and publish without opening GitHub."],["services","Update a service","Change words, images, pricing and calls to action."],["media","Manage media","Upload an image once, then reuse it where you need it."],["burt","Burt","Change his customer-facing welcome and helpful links."]].map(([id,title,copy])=><button key={id} className="admin-card" onClick={()=>go(id as Section)}><b>{title} →</b><span>{copy}</span></button>)}</div></>}

function Blog({rows,refresh,tell}:{rows:Row[];refresh:()=>Promise<void>;tell:(s:string)=>void}){const [editing,setEditing]=useState<Row|null>(null);const empty={title:"",slug:"",excerpt:"",body_html:"<p></p>",featured_image_alt:"",author:"Marnie Danson",status:"draft",seo_title:"",meta_description:""};const save=async()=>{if(!editing||!supabase)return;const item={...editing,slug:slugify(editing.slug||editing.title),body_html:safeHtml(editing.body_html||""),published_at:editing.status==="published"?(editing.published_at||new Date().toISOString()):null};const {error}=editing.id?await supabase.from("cms_posts").update(item).eq("id",editing.id):await supabase.from("cms_posts").insert(item);tell(error?error.message:"Post saved.");if(!error){setEditing(null);await refresh();}};return <><p className="admin-eyebrow">BLOG</p><h1>Useful bits. No waffle.</h1>{!editing?<><button className="admin-primary" onClick={()=>setEditing(empty)}>New post →</button><List rows={rows} edit={setEditing} remove={async id=>{if(confirm("Delete this post? This cannot be undone.")){await supabase?.from("cms_posts").delete().eq("id",id);await refresh();}}} preview="blog"/></>:<PostEditor value={editing} setValue={setEditing} save={save} cancel={()=>setEditing(null)}/>}</>}

function List({rows,edit,remove,preview}:{rows:Row[];edit:(x:Row)=>void;remove:(id:string)=>void;preview?:string}){return <div className="admin-list">{rows.map(x=><article key={x.id}><div><small>{x.status || (x.is_visible?"visible":"hidden")}</small><h2>{x.title||x.service_name||x.person_name}</h2><p>{x.slug?`/${x.slug}/`:x.quote}</p></div><div><button onClick={()=>edit(x)}>Edit</button>{preview&&<button onClick={()=>window.open(`/blog/${x.slug}/?preview=1`,`_blank`)}>Preview</button>}<button className="danger" onClick={()=>remove(x.id)}>Delete</button></div></article>)}{!rows.length&&<p>Nothing here yet.</p>}</div>}

function PostEditor({value,setValue,save,cancel}:{value:Row;setValue:(x:Row)=>void;save:()=>void;cancel:()=>void}){const set=(k:string,v:any)=>setValue({...value,[k]:v});return <div className="admin-editor"><div className="admin-editor__bar"><button onClick={()=>document.execCommand("bold")}>Bold</button><button onClick={()=>document.execCommand("italic")}>Italic</button><button onClick={()=>document.execCommand("formatBlock",false,"h2")}>H2</button><button onClick={()=>document.execCommand("formatBlock",false,"h3")}>H3</button><button onClick={()=>document.execCommand("insertUnorderedList")}>List</button><button onClick={()=>document.execCommand("formatBlock",false,"blockquote")}>Quote</button></div><Field label="Title" value={value.title} set={v=>{set("title",v);if(!value.slug)set("slug",slugify(v));}}/><Field label="URL slug" value={value.slug} set={v=>set("slug",slugify(v))}/><Area label="Excerpt" value={value.excerpt} set={v=>set("excerpt",v)}/><label>Article content<div className="rich-editor" contentEditable suppressContentEditableWarning onInput={e=>set("body_html",(e.currentTarget as HTMLDivElement).innerHTML)} dangerouslySetInnerHTML={{__html:value.body_html||""}}/></label><Field label="Featured image alt text" value={value.featured_image_alt} set={v=>set("featured_image_alt",v)}/><Field label="Author" value={value.author} set={v=>set("author",v)}/><label>Status<select value={value.status} onChange={e=>set("status",e.target.value)}><option value="draft">Draft</option><option value="published">Published</option></select></label><details><summary>SEO settings</summary><Field label="SEO title" value={value.seo_title||""} set={v=>set("seo_title",v)}/><Area label="Meta description" value={value.meta_description||""} set={v=>set("meta_description",v)}/></details><Actions save={save} cancel={cancel} label={value.status==="published"?"Save and publish":"Save draft"}/></div>}

function Services({rows,refresh}:{rows:Row[];refresh:()=>Promise<void>}){const [editing,setEditing]=useState<Row|null>(null);const save=async()=>{if(!editing||!supabase)return;const {error}=editing.id?await supabase.from("cms_services").update(editing).eq("id",editing.id):await supabase.from("cms_services").insert(editing);if(error)alert(error.message);else{setEditing(null);await refresh();}};return <><p className="admin-eyebrow">SERVICES</p><h1>Keep the words and images current.</h1>{!editing?<><button className="admin-primary" onClick={()=>setEditing({slug:"",service_name:"",short_description:"",main_copy:"",cta_label:"Work with me →",cta_href:"/work-with-me/",is_visible:true,display_order:rows.length})}>Add service →</button><List rows={rows} edit={setEditing} remove={async id=>{if(confirm("Delete this service?")){await supabase?.from("cms_services").delete().eq("id",id);await refresh();}}}/></>:<ServiceEditor value={editing} setValue={setEditing} save={save} cancel={()=>setEditing(null)}/>}</>}
function ServiceEditor({value,setValue,save,cancel}:{value:Row;setValue:(x:Row)=>void;save:()=>void;cancel:()=>void}){const set=(k:string,v:any)=>setValue({...value,[k]:v});return <div className="admin-editor"><Field label="Service name" value={value.service_name} set={v=>{set("service_name",v);if(!value.slug)set("slug",slugify(v));}}/><Field label="Slug" value={value.slug} set={v=>set("slug",slugify(v))}/><Area label="Short description" value={value.short_description} set={v=>set("short_description",v)}/><Area label="Main copy" value={value.main_copy} set={v=>set("main_copy",v)}/><Field label="Starting price" value={value.starting_price||""} set={v=>set("starting_price",v)}/><Field label="Hero image path" value={value.hero_image_path||""} set={v=>set("hero_image_path",v)}/><Field label="Hero image alt text" value={value.hero_image_alt||""} set={v=>set("hero_image_alt",v)}/><Field label="CTA wording" value={value.cta_label} set={v=>set("cta_label",v)}/><Field label="CTA destination" value={value.cta_href} set={v=>set("cta_href",v)}/><label><input type="checkbox" checked={value.is_visible} onChange={e=>set("is_visible",e.target.checked)}/> Visible on public site</label><details><summary>SEO settings</summary><Field label="SEO title" value={value.seo_title||""} set={v=>set("seo_title",v)}/><Area label="Meta description" value={value.meta_description||""} set={v=>set("meta_description",v)}/></details><Actions save={save} cancel={cancel} label="Save service"/></div>}

function Reviews({rows,refresh}:{rows:Row[];refresh:()=>Promise<void>}){const [editing,setEditing]=useState<Row|null>(null);const save=async()=>{if(!editing)return;const {error}=editing.id?await supabase!.from("cms_reviews").update(editing).eq("id",editing.id):await supabase!.from("cms_reviews").insert(editing);if(error)alert(error.message);else{setEditing(null);await refresh();}};return <><p className="admin-eyebrow">REVIEWS</p><h1>Nice things people said about you.</h1>{!editing?<><button className="admin-primary" onClick={()=>setEditing({quote:"",person_name:"",person_role:"",source:"",rating:5,is_visible:true,display_order:rows.length})}>Add review →</button><List rows={rows} edit={setEditing} remove={async id=>{if(confirm("Delete this review?")){await supabase!.from("cms_reviews").delete().eq("id",id);await refresh();}}}/></>:<div className="admin-editor"><Area label="Quote" value={editing.quote} set={v=>setEditing({...editing,quote:v})}/><Field label="Name" value={editing.person_name} set={v=>setEditing({...editing,person_name:v})}/><Field label="Role / context" value={editing.person_role||""} set={v=>setEditing({...editing,person_role:v})}/><Field label="Source" value={editing.source||""} set={v=>setEditing({...editing,source:v})}/><label>Rating<input type="number" min="1" max="5" value={editing.rating||5} onChange={e=>setEditing({...editing,rating:Number(e.target.value)})}/></label><label><input type="checkbox" checked={editing.is_visible} onChange={e=>setEditing({...editing,is_visible:e.target.checked})}/> Show publicly</label><Actions save={save} cancel={()=>setEditing(null)} label="Save review"/></div>}</>}

function Media({rows,refresh}:{rows:Row[];refresh:()=>Promise<void>}){const [uploading,setUploading]=useState(false);const upload=async(e:React.ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file||!supabase)return;if(!/^image\/(jpeg|png|webp|gif)$/.test(file.type)||file.size>10485760){alert("Use a JPG, PNG, WebP or GIF under 10MB.");return;}setUploading(true);const path=`${new Date().toISOString().slice(0,10)}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,"-")}`;const {error}=await supabase.storage.from("cms-media").upload(path,file,{contentType:file.type});if(error)alert(error.message);else{await supabase.from("cms_media").insert({storage_path:path,file_name:file.name,mime_type:file.type,bytes:file.size,alt_text:""});await refresh();}setUploading(false);};return <><p className="admin-eyebrow">MEDIA</p><h1>Website images.</h1><p className="admin-lead">JPG, PNG, WebP or GIF up to 10MB. Give every image proper alt text before using it publicly.</p><label className="admin-primary upload">{uploading?"Uploading…":"Upload image →"}<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" onChange={upload} hidden/></label><div className="media-grid">{rows.map(x=>{const src=supabase!.storage.from("cms-media").getPublicUrl(x.storage_path).data.publicUrl;return <figure key={x.id}><img src={src} alt={x.alt_text||""}/><figcaption>{x.file_name}</figcaption></figure>})}</div></>}

function Settings({title,settingKey,value,refresh,burt=false}:{title:string;settingKey:string;value:Row;refresh:()=>Promise<void>;burt?:boolean}){const [state,setState]=useState(value);useEffect(()=>setState(value),[value]);const save=async()=>{const {error}=await supabase!.from("cms_settings").upsert({setting_key:settingKey,setting_value:state});if(error)alert(error.message);else{alert(`${title} saved.`);await refresh();}};return <><p className="admin-eyebrow">{burt?"ASK BURT":"GLOBAL DETAILS"}</p><h1>{title}</h1><div className="admin-editor">{burt?<><label><input type="checkbox" checked={state.enabled!==false} onChange={e=>setState({...state,enabled:e.target.checked})}/> Burt enabled</label><Area label="Welcome text" value={state.welcome_text||""} set={v=>setState({...state,welcome_text:v})}/><Area label="Human / WhatsApp wording" value={state.human_contact_text||""} set={v=>setState({...state,human_contact_text:v})}/><Field label="WhatsApp destination" value={state.whatsapp_url||""} set={v=>setState({...state,whatsapp_url:v})}/><Field label="Book a Time destination" value={state.book_url||"/book/"} set={v=>setState({...state,book_url:v})}/><Field label="Work With Me destination" value={state.work_with_me_url||"/work-with-me/"} set={v=>setState({...state,work_with_me_url:v})}/></>:<><Field label="Business name" value={state.business_name||""} set={v=>setState({...state,business_name:v})}/><Field label="Contact email" value={state.contact_email||""} set={v=>setState({...state,contact_email:v})}/><Field label="Booking URL" value={state.booking_url||""} set={v=>setState({...state,booking_url:v})}/><Field label="Location" value={state.location||""} set={v=>setState({...state,location:v})}/><Field label="Worldwide line" value={state.worldwide||""} set={v=>setState({...state,worldwide:v})}/></>}<button className="admin-primary" onClick={save}>Save {title}</button></div></>}
function Pages(){return <><p className="admin-eyebrow">PAGES</p><h1>Protected page structure.</h1><p className="admin-lead">Safe page content controls are ready for Home, About, Services, Work With Me and Book. Their approved layout, navigation and design stay locked.</p><p>The existing approved wording has not been replaced or changed.</p></>}
function Seo({posts,services}:{posts:Row[];services:Row[]}){return <><p className="admin-eyebrow">SEO</p><h1>Titles, descriptions and sharing images.</h1><p className="admin-lead">Blog posts and services have their own SEO fields in their editor. Page-level SEO will live here after each existing approved page is deliberately migrated.</p><p>{posts.length} blog posts and {services.length} service records are ready to manage.</p></>}
function Field({label,value,set}:{label:string;value:any;set:(v:string)=>void}){return <label>{label}<input value={value??""} onChange={e=>set(e.target.value)}/></label>}
function Area({label,value,set}:{label:string;value:any;set:(v:string)=>void}){return <label>{label}<textarea value={value??""} onChange={e=>set(e.target.value)}/></label>}
function Actions({save,cancel,label}:{save:()=>void;cancel:()=>void;label:string}){return <div className="admin-actions"><button className="admin-primary" onClick={save}>{label}</button><button onClick={cancel}>Cancel</button></div>}
